[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "infosoft-info-subscription"
version = "0.0.1"
description = "INFO-Subscription API Python SDK"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
keywords = ["infosoft", "info-subscription", "sdk"]
dependencies = [
    "microsoft-kiota-bundle>=1.9.8",
    "msal>=1.31.0",
]

[project.urls]
Homepage = "https://github.com/infosoftas/info-subscription-sdk"
Repository = "https://github.com/infosoftas/info-subscription-sdk"

[tool.hatch.build.targets.wheel]
packages = ["src/info_subscription_sdk"]
